name: Create Release

on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: NPM Install Json
        id: install-json
        run: npm i -g json
      
      - name: NPM List Dependencies
        id: list-dependencies
        run: |
          json dependencies -a < package.json | grep : | sed 's/^ *//;s/"//g;s/: /@/;s/,$//'

      - name: Print Dependencies
        id: print-dependencies
        run: |
          echo "Dependencies: ${{ steps.list-dependencies.outputs }}"

      - name: Create Release
        id: create_release
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ## ChangeLog            
            ### Added:              
              - feature1
            ### Improvements:
              - improve1
            ### Bug fixes:
              - bug1
            ### Depedencies:
              - ${{ steps.list-dependencies.outputs }}
          draft: false
          prerelease: false
          generate_release_notes: true