name: Create Release

on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print Tag Name
        id: tag_name_output
        run: echo "TAG_NAME = ${{ github.ref }}"
      - name: Create Release
        id: create_release
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          generate_release_notes: true